linuxdeepin/dde-file-manager-extensions

src/dde-file-manager/dfmplugin-disk-encrypt-entry/CMakeLists.txt
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/encryptparamsinputdialog.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/encryptparamsinputdialog.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/utils/encryptutils.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/utils/encryptutils.h

as title.
Log: implement user interactive

feat: [ui] encrypt entry user interactive.

---

assets/polkit/com.deepin.filemanager.daemon.diskencrypt.policy
debian/dfmplugin-disk-encrypt1.install
src/dde-file-manager-daemon/daemonplugin-file-encrypt/CMakeLists.txt
src/dde-file-manager-daemon/daemonplugin-file-encrypt/daemonplugin_file_encrypt_global.h
src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.h
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/diskencrypt.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/CMakeLists.txt
src/dde-file-manager/dfmplugin-disk-encrypt-entry/dfmplugin_disk_encrypt_global.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/decryptparamsinputdialog.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/encryptparamsinputdialog.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/encryptparamsinputdialog.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/plugin_diskencryptentry.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/utils/encryptutils.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/utils/encryptutils.h
translations/disk-encrypt.ts
translations/disk-encrypt_zh_CN.ts

feat: [encrypt] encrypt params for fstab device.

---

src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/diskencrypt.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/dfmplugin_disk_encrypt_global.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/encryptparamsinputdialog.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/encryptparamsinputdialog.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/utils/encryptutils.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/utils/encryptutils.h

add tpm encrypt code.
Log: add tpm encrypt code

feat: [tpm] add tpm function

---

debian/control
src/dde-file-manager-daemon/daemonplugin-file-encrypt/CMakeLists.txt
src/dde-file-manager-daemon/daemonplugin-file-encrypt/daemonplugin_file_encrypt_global.h
src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.h
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/diskencrypt.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/diskencrypt.h
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/dfmplugin_disk_encrypt_global.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/acquirepindialog.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/acquirepindialog.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/chgpassphrasedialog.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/chgpassphrasedialog.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/decryptparamsinputdialog.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/encryptparamsinputdialog.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/plugin_diskencryptentry.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/plugin_diskencryptentry.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/utils/encryptutils.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/utils/encryptutils.h
translations/disk-encrypt.ts
translations/disk-encrypt_zh_CN.ts

1. as title;
2. impl recovery key export.
Log: implement change passphrase of device.

实现密钥修改及恢复密钥导出功能

---

debian/changelog
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/diskencrypt.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/decryptparamsinputdialog.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/decryptparamsinputdialog.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp
translations/disk-encrypt.ts
translations/disk-encrypt_zh_CN.ts

- fix: [encrypt] memleak
- chore: [chglog] update version to 1.0.0

处理内存泄漏及更新基线版本

---

CMakeLists.txt

as title.
Log: update cmake list.

尝试修复CRP编译问题

---

src/dde-file-manager/dfmplugin-disk-encrypt-entry/dfmplugin_disk_encrypt_global.h

feat: [tpm] change the password size

---

debian/control

as title.
Log: fix compile issue.

修复 CRP 编译问题3

---

debian/changelog
debian/control
debian/copyright
src/dde-file-manager/dfmplugin-disk-encrypt-entry/CMakeLists.txt

as title.
Log: fix compile issue.

修复 crp 构建依赖问题

---

debian/control

as title.
Log: remove build dependency version limit.

移除编译依赖中的文管版本限制

---

assets/configs/org.deepin.dde.file-manager.diskencrypt.json
debian/control
src/dde-file-manager-daemon/daemonplugin-file-encrypt/CMakeLists.txt
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/diskencrypt.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/diskencrypt.h

as title, use QLibrary to dynamic load.
Log: remove libusec-recoverykey dependency.

移除libusec-recoverykey编译依赖，使用动态加载

---

debian/control
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/diskencrypt.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/plugin_diskencryptentry.cpp
translations/disk-encrypt.ts
translations/disk-encrypt_zh_CN.ts

调整加密模式解析方式；修改cryptsetup版本限制为>=2:2.3.7

---

debian/changelog

更新1070分支版本号

---

src/dde-file-manager/dfmplugin-disk-encrypt-entry/dfmplugin_disk_encrypt_global.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/encryptparamsinputdialog.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/encryptparamsinputdialog.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/plugin_diskencryptentry.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/utils/encryptutils.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/utils/encryptutils.h
src/dde-file-manager/dfmplugin-encrypt-manager/encrypt_manager_global.h
src/dde-file-manager/dfmplugin-encrypt-manager/encryptmanager.h
src/dde-file-manager/dfmplugin-encrypt-manager/events/eventreceiver.cpp
src/dde-file-manager/dfmplugin-encrypt-manager/events/eventreceiver.h
src/dde-file-manager/dfmplugin-encrypt-manager/tpm/tpmwork.cpp
src/dde-file-manager/dfmplugin-encrypt-manager/tpm/tpmwork.h
src/demo/dfmplugin-encrypt-manager-demo/mainwindow.cpp
src/demo/dfmplugin-encrypt-manager-demo/mainwindow.h

add tcm support in disk encrypt

feat: [tcm] add tcm support

---

src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/chgpassphrasedialog.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/decryptparamsinputdialog.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/encryptprocessdialog.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/utils/encryptutils.cpp
translations/disk-encrypt.ts
translations/disk-encrypt_zh_CN.ts

as title.
Log: fix some ui issue.
Bug: https://pms.uniontech.com/bug-view-229137.html

修复一些UI上的问题

---

assets/polkit/policy/com.deepin.filemanager.daemon.diskencrypt.policy
assets/polkit/rules/99-dde-file-manager-encrypt.pkla
debian/dfmplugin-disk-encrypt1.install
src/dde-file-manager-daemon/daemonplugin-file-encrypt/CMakeLists.txt
src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.h

- feat: [encrypt] finish encrypt of fstab devices
- fix: [polkit] add rules to skip some auth action

支持fstab磁盘加密（需系统安全支持）、解锁磁盘跳过polkit验证

---

debian/control

add tpm2-abrmd libtss2-tcti-pcap0
Log: as title.

feat: [debian] add runtime dependencies.

---

debian/changelog
src/dde-file-manager-daemon/daemonplugin-file-encrypt/daemonplugin_file_encrypt_global.h
src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.h
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/diskencrypt.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/diskencrypt.h
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.h
src/dde-file-manager-daemon/daemonplugin-file-encrypt/globaltypesdefine.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/CMakeLists.txt
src/dde-file-manager/dfmplugin-disk-encrypt-entry/dfmplugin_disk_encrypt_global.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/events/eventshandler.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/chgpassphrasedialog.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/encryptparamsinputdialog.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/encryptparamsinputdialog.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/utils/encryptutils.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/utils/encryptutils.h
translations/disk-encrypt.ts
translations/disk-encrypt_zh_CN.ts

as title.
Log: set tpm token to device.
Bug: ttps://pms.uniontech.com/bug-view-232673.html

使用 token 来记录 tpm 相关的配置

---

src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/chgpassphrasedialog.cpp
translations/disk-encrypt.ts
translations/disk-encrypt_zh_CN.ts

as title.
Log: update translation.

chore: [translation] update translation.

---

src/dde-file-manager/dfmplugin-disk-encrypt-entry/dfmplugin_disk_encrypt_global.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/encryptparamsinputdialog.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/encryptparamsinputdialog.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/utils/encryptutils.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/utils/encryptutils.h
src/dde-file-manager/dfmplugin-encrypt-manager/encrypt_manager_global.h
src/dde-file-manager/dfmplugin-encrypt-manager/events/eventreceiver.cpp
src/dde-file-manager/dfmplugin-encrypt-manager/events/eventreceiver.h
src/dde-file-manager/dfmplugin-encrypt-manager/tpm/tpmwork.cpp
src/dde-file-manager/dfmplugin-encrypt-manager/tpm/tpmwork.h
src/demo/dfmplugin-encrypt-manager-demo/mainwindow.cpp
src/demo/dfmplugin-encrypt-manager-demo/mainwindow.h

fix: [TPM] add pcr and pin mode

---

src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/utils/encryptutils.cpp

as title..
Log: fix issue about passphrase modify
Bug: https://pms.uniontech.com/bug-view-232673.html

fix: [tpm] adopt the tpm config with usec

---

src/dde-file-manager/dfmplugin-disk-encrypt-entry/utils/encryptutils.cpp

fix: [TPM] change the return code

---

src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp

as title.
Log: fix issue about menu entry.
Bug: https://pms.uniontech.com/bug-view-232171.html

修复lvm逻辑卷显示加密入口的问题

---

src/dde-file-manager/dfmplugin-disk-encrypt-entry/utils/encryptutils.cpp

fix: [tpm] add custom pcr when decrypt

---

src/dde-file-manager/dfmplugin-encrypt-manager/encrypt_manager_global.h
src/dde-file-manager/dfmplugin-encrypt-manager/events/eventreceiver.cpp
src/dde-file-manager/dfmplugin-encrypt-manager/events/eventreceiver.h
src/dde-file-manager/dfmplugin-encrypt-manager/tpm/tpmwork.cpp
src/dde-file-manager/dfmplugin-encrypt-manager/tpm/tpmwork.h
src/demo/dfmplugin-encrypt-manager-demo/mainwindow.cpp
src/demo/dfmplugin-encrypt-manager-demo/mainwindow.h

fix: [tpm] add TPM return code

---

src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.h

as title.
Log: fix issue about crypttab modify
Bug: https://pms.uniontech.com/bug-view-234647.html

修复 crypttab 中配置项被误删除的问题

---

debian/control
debian/dfmplugin-cooperation.install
src/dde-file-manager/CMakeLists.txt
src/dde-file-manager/dfmplugin-cooperation/CMakeLists.txt
src/dde-file-manager/dfmplugin-cooperation/configs/dconfig/dconfigmanager.cpp
src/dde-file-manager/dfmplugin-cooperation/configs/dconfig/dconfigmanager.h
src/dde-file-manager/dfmplugin-cooperation/configs/dconfig/dconfigmanager_p.h
src/dde-file-manager/dfmplugin-cooperation/configs/settings/configmanager.cpp
src/dde-file-manager/dfmplugin-cooperation/configs/settings/configmanager.h
src/dde-file-manager/dfmplugin-cooperation/configs/settings/settings.cpp
src/dde-file-manager/dfmplugin-cooperation/configs/settings/settings.h
src/dde-file-manager/dfmplugin-cooperation/cooperationplugin.cpp
src/dde-file-manager/dfmplugin-cooperation/cooperationplugin.h
src/dde-file-manager/dfmplugin-cooperation/cooperationplugin.json
src/dde-file-manager/dfmplugin-cooperation/dialogs/filetransfersettingsdialog.cpp
src/dde-file-manager/dfmplugin-cooperation/dialogs/filetransfersettingsdialog.h
src/dde-file-manager/dfmplugin-cooperation/menu/cooperationmenuscene.cpp
src/dde-file-manager/dfmplugin-cooperation/menu/cooperationmenuscene.h
src/dde-file-manager/dfmplugin-cooperation/menu/cooperationmenuscene_p.h
src/dde-file-manager/dfmplugin-cooperation/utils/cooperationhelper.cpp
src/dde-file-manager/dfmplugin-cooperation/utils/cooperationhelper.h

Move the file deliver DFM plugin from dde-cooperation project to this, it requires 6.0.30+ dfm.
Log: add file deliver plugin.

feat: Add cooperation file deliver plugin

---

debian/dfmplugin-cooperation.install
debian/dfmplugin-disk-encrypt.install
src/dde-file-manager/dfmplugin-cooperation/CMakeLists.txt
src/dde-file-manager/dfmplugin-cooperation/cooperationplugin.cpp
src/dde-file-manager/dfmplugin-cooperation/menu/cooperationmenuscene.cpp
translations/cooperation-transfer.ts
translations/cooperation-transfer_zh_CN.ts

Move the menu from `share` to `send to`
Log: new feature
Task: https://pms.uniontech.com/task-view-310399.html

feat: [cooperation] Adaptive menu item modification

---

src/dde-file-manager/dfmplugin-cooperation/CMakeLists.txt

fix: fix the Fix packaging issue

---

src/dde-file-manager/dfmplugin-disk-encrypt-entry/events/eventshandler.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/events/eventshandler.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/unlockpartitiondialog.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/utils/encryptutils.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/utils/encryptutils.h
translations/disk-encrypt.ts
translations/disk-encrypt_zh_CN.ts

as title.
Log: as title.
Bug: https://pms.uniontech.com/bug-view-229113.html

TPM不可用时提示使用恢复秘钥解锁

---

src/dde-file-manager/dfmplugin-disk-encrypt-entry/events/eventshandler.cpp

as title.
Log: as title.
Bug: https://pms.uniontech.com/bug-view-229113.html

使用更简单和快速的方法判定tpm可用状态

---

debian/dfmplugin-disk-encrypt.postinst
src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.cpp

- fix: [encrypt] cannot launch system after encrypted
- feat: [daemon] add postinst to enable daemon process.

文管守护进程自启、crypttab 按需更新

---

src/dde-file-manager/dfmplugin-disk-encrypt-entry/events/eventshandler.cpp
translations/disk-encrypt.ts
translations/disk-encrypt_zh_CN.ts

as title.
Log: as title.
Bug: https://pms.uniontech.com/bug-view-232585.html

修改口令/PIN码的文案

---

debian/control

添加tpm相关运行依赖

---

debian/control

chore: [dep] add dependency libtss2-tcti-tabrmd0

---

src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.h

更新 initramfs 时阻塞重启操作

---

.tx/config
.tx/deepin.conf

add language setting
Log: add language setting
Bug: no

fix: add language setting

---

src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.h

fix: [decrypt] cannot find device by UUID

---

src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.cpp

fix: [decrypt] cannot find device by UUID v2.

---

debian/changelog
src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.h
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/globaltypesdefine.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp

as title.
remove the operation of update-initramfs
update version to 1.1.7
Log: as title.

feat: [encrypt] disable encrypt for / & /recovery.

---

debian/changelog

chore: [chglog] update version to 1.1.8

---

src/dde-file-manager/dfmplugin-cooperation/CMakeLists.txt
src/dde-file-manager/dfmplugin-cooperation/cooperationplugin.cpp
src/dde-file-manager/dfmplugin-cooperation/dialogs/filetransfersettingsdialog.cpp
src/dde-file-manager/dfmplugin-cooperation/reportlog/datas/cooperationreportdata.cpp
src/dde-file-manager/dfmplugin-cooperation/reportlog/datas/cooperationreportdata.h
src/dde-file-manager/dfmplugin-cooperation/reportlog/datas/reportdatainterface.h
src/dde-file-manager/dfmplugin-cooperation/reportlog/reportlogmanager.cpp
src/dde-file-manager/dfmplugin-cooperation/reportlog/reportlogmanager.h
src/dde-file-manager/dfmplugin-cooperation/reportlog/reportlogworker.cpp
src/dde-file-manager/dfmplugin-cooperation/reportlog/reportlogworker.h

Log: add buried information in dde-cooperation of dde-file-manager
Bug: https://pms.uniontech.com/bug-view-239657.html

fix: add buried information in dde-cooperation of dde-file-manager

---

src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/diskencrypt.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/diskencrypt.h
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.h

as title.
Log: as title.
Task: https://pms.uniontech.com/task-view-323141.html

feat: [encrypt] disbale ab recovery after encrypted

---

src/dde-file-manager/dfmplugin-disk-encrypt-entry/events/eventshandler.cpp

chore: [encrypt] cursor error

---

src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/encryptparamsinputdialog.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/encryptprogressdialog.cpp
translations/disk-encrypt_zh_CN.ts

as title
Log: as title.
Bug: https://pms.uniontech.com/bug-view-242951.html

fix: [encrypt] hint when export to a readonly partition

---

src/dde-file-manager/dfmplugin-disk-encrypt-entry/events/eventshandler.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/chgpassphrasedialog.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/decryptparamsinputdialog.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/encryptparamsinputdialog.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/unlockpartitiondialog.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/utils/encryptutils.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/utils/encryptutils.h

always show execed-dialog on top layer.(only on wayland).
Log: as title
Bug: https://pms.uniontech.com/bug-view-241989.html

fix: [UI] the modaled dialog layer.

---

src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/encryptparamsinputdialog.cpp

as title.
Log: as title.
Bug: https://pms.uniontech.com/bug-view-242879.html

fix: [encrypt] remove TPM options if not support

---

debian/changelog
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.h
src/dde-file-manager-daemon/daemonplugin-file-encrypt/globaltypesdefine.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/events/eventshandler.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/events/eventshandler.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/encryptparamsinputdialog.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/encryptprogressdialog.cpp

- feat: [encrypt] auto start dfm after device encrypted
- feat: [encrypt] texts change.

interaction modify

---

src/dde-file-manager/dfmplugin-disk-encrypt-entry/events/eventshandler.cpp

as title.
Log: as title.
Task: https://pms.uniontech.com/task-view-326333.html

feat: [encrypt] text changes

---

src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/diskencrypt.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/diskencrypt.h
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.cpp

as title
Log: as title.
Bug: https://pms.uniontech.com/bug-view-243179.html

fix: [encrypt] try open dev before resume reencryption

---

.reuse/dep5
src/dde-desktop/ddplugin-videowallpaper/CMakeLists.txt
src/dde-desktop/ddplugin-videowallpaper/ddplugin_videowallpaper_global.h
src/dde-desktop/ddplugin-videowallpaper/videoproxy.cpp
src/dde-desktop/ddplugin-videowallpaper/videoproxy.h
src/dde-desktop/ddplugin-videowallpaper/videowallpapermenuscene.cpp
src/dde-desktop/ddplugin-videowallpaper/videowallpapermenuscene.h
src/dde-desktop/ddplugin-videowallpaper/videowallpaperplugin.cpp
src/dde-desktop/ddplugin-videowallpaper/videowallpaperplugin.h
src/dde-desktop/ddplugin-videowallpaper/wallpaperconfig.cpp
src/dde-desktop/ddplugin-videowallpaper/wallpaperconfig.h
src/dde-desktop/ddplugin-videowallpaper/wallpaperconfig_p.h
src/dde-desktop/ddplugin-videowallpaper/wallpaperengine.cpp
src/dde-desktop/ddplugin-videowallpaper/wallpaperengine.h
src/dde-desktop/ddplugin-videowallpaper/wallpaperengine_p.h

fix: add lisence

---

src/dde-desktop/CMakeLists.txt

fix: [desktop] anotate the wallpaper plugin

---

CMakeLists.txt

fix: [desktop] crp issue

---

CMakeLists.txt
debian/control
src/dde-desktop/CMakeLists.txt

fix: [crp] build issue

---

src/dde-desktop/CMakeLists.txt

chore: [crp] no wallpaper plugin

---

assets/configs/org.deepin.dde.file-manager.diskencrypt.json
src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/utils/encryptutils.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/utils/encryptutils.h

feat: [encrypt] add config to control the feature.

---

src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/events/eventshandler.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/chgpassphrasedialog.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/decryptparamsinputdialog.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/encryptparamsinputdialog.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/utils/encryptutils.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/utils/encryptutils.h

fix: [encrypt] cursor, widget focus, tpm block thread

---

src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/diskencrypt.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/globaltypesdefine.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp

Add separation header part encrypt logic code
Log: add feature of separation header part encrypt. Task:

feat: [part-encrypt] Add separation header part encrypt logic code

---

src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/events/eventshandler.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/encryptparamsinputdialog.cpp

- **fix: [encrypt] cannot find encrypt config.**
- **fix: [247503/encrypt] dialog raises after cancelled.**
- **fix: [247533/encrypt] device name in input dialog.**

interact optimize

---

src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/diskencrypt.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.h
src/dde-file-manager-daemon/daemonplugin-file-encrypt/globaltypesdefine.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp

1. Change fs_passno when encrypting.
2. Change /etc/crypttab when tpm encrpted.
3. Change var name.

feat: [detached-header] Change fs_passno when encrypting.

---

src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/diskencrypt.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.h
src/dde-file-manager-daemon/daemonplugin-file-encrypt/globaltypesdefine.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp

add encrypt logic for detached-header

feat: [detached-header] add encrypt logic for detached-header

---

src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/diskencrypt.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/diskencrypt.h

add function to get if device has an encrypt config.
Log: as title.
Bug: https://pms.uniontech.com/bug-view-248515.html

fix: [248515/encrypt] resume encrypt

---

src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.h
src/dde-file-manager-daemon/daemonplugin-file-encrypt/globaltypesdefine.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp

feat: [encrypt] decrypt fstab device by PARTUUID

---

src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/encryptparamsinputdialog.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/gui/encryptparamsinputdialog.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/utils/encryptutils.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/utils/encryptutils.h
src/dde-file-manager/dfmplugin-encrypt-manager/encryptmanager.h
src/dde-file-manager/dfmplugin-encrypt-manager/events/eventreceiver.cpp
src/dde-file-manager/dfmplugin-encrypt-manager/events/eventreceiver.h
src/dde-file-manager/dfmplugin-encrypt-manager/tpm/tpmwork.cpp
src/dde-file-manager/dfmplugin-encrypt-manager/tpm/tpmwork.h
translations/disk-encrypt_zh_CN.ts

as title.
Log: as title.
Bug: https://pms.uniontech.com/bug-view-247049.html

fix: [247049/encrypt] report error if TPM locked.

---

src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp

feat: [decrypt] set fs no check before decrytp device

---

debian/changelog

as title.
Log: update version.

chore: [chglog] update version to 1.1.12

---

src/dde-file-manager-daemon/daemonplugin-file-encrypt/daemonplugin_file_encrypt_global.h
src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.h
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/diskencrypt.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/diskencrypt.h
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/globaltypesdefine.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/events/eventshandler.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/events/eventshandler.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/plugin_diskencryptentry.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/plugin_diskencryptentry.h

- **fix: [249095/decrypt] continue decrypt after interrupted.**
- **fix: [249099/decrypt] continue decrypt after interrupted.**

decrypt error

---

debian/changelog

chore: [chglog] update version to 1.1.13

---

src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.h
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/globaltypesdefine.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/events/eventshandler.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp

if it's not encrypted anymore.
Log: as title.

fix: [crypttab] delete items in crypttab.

---

src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/diskencrypt.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/diskencrypt.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/events/eventshandler.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/events/eventshandler.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/plugin_diskencryptentry.cpp

- **fix: [249531/encrypt] redecrypt, dev status, menu entry.**
- **chore: [translate] update translation.**
- **fix: [249587/decrypt] re-decrypt after interrupted.**

disable unlock if decrypt

---

translations/disk-encrypt_zh_CN.ts

chore: [translate] update translations.

---

src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/diskencrypt.cpp

chore: [decrypt] update progress

---

src/dde-file-manager/dfmplugin-cooperation/menu/cooperationmenuscene.cpp

[menu] only one action in send to
Log: [menu] only one action in send to
Bug: https://pms.uniontech.com/bug-view-247351.html

fix: [menu] only one action in send to

---

debian/changelog

as title.
Log: version update.

chore: [chglog] update version to 1.1.14

---

assets/configs/org.deepin.dde.file-manager.diskencrypt.json
debian/changelog

and update change log.
Log: as title.
Bug: https://pms.uniontech.com/bug-view-251293.html

fix: [251293/encrypt] disable encrypt by default

---

src/dde-desktop/CMakeLists.txt
src/dde-file-manager-daemon/daemonplugin-file-encrypt/globaltypesdefine.h

and fix V23 compile issue.
Log: as title.

chore: [wallpaper] active plugin.

---

debian/changelog

as title.
Log: version update.

chore: [chglog] update version to 1.1.15

---

debian/changelog
src/dde-desktop/ddplugin-videowallpaper/CMakeLists.txt

install video wallpaper for all edtion
Log: 
Task: https://pms.uniontech.com/task-view-350675.html

feat: install video wallpaper for all edtion

---

src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.h
translations/disk-encrypt.ts
translations/disk-encrypt_zh_CN.ts

[safety] encrypt dbus input
Log: [safety] encrypt dbus input
Bug: https://pms.uniontech.com/bug-view-259823.html

feat: [safety] encrypt dbus input

---

src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp

remove string encrypt plugin.
Log: remove string encrypt plugin.
Bug: https://pms.uniontech.com/bug-view-262843.html

fix: [safety] remove string encrypt plugin.

---

src/dde-file-manager/dfmplugin-cooperation/CMakeLists.txt
translations/disk-encrypt.ts
translations/disk-encrypt_zh_CN.ts

chore: fix build failed in v23

---

src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/dbus/diskencryptdbus.h
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.h

The desktop not create when encrypt normal disk.
Log: fix issue
Bug: https://pms.uniontech.com/bug-view-250465.html

fix: [disk-encrypt] The dde-file-manage not auto start

---

src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/diskencrypt.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/encryptworker.cpp
src/dde-file-manager-daemon/daemonplugin-file-encrypt/globaltypesdefine.h
src/dde-file-manager/dfmplugin-disk-encrypt-entry/events/eventshandler.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp

Set the device to partUuid.
Log: fix issue
Bug: https://pms.uniontech.com/bug-view-263863.html

fix: [part-encrypt] Set the device to partUuid.

---

debian/changelog

update change log to version 1.1.17

chore: [change-log] update change log

---

src/CMakeLists.txt

chore: for refresh version.

---

debian/dfmplugin-disk-encrypt.postinst

make it always true.
Log: as title
Bug: https://pms.uniontech.com/task-view-359801.html

fix: [upgrade] script failed blocks upgrade.

---

src/dde-file-manager/dfmplugin-disk-encrypt-entry/events/eventshandler.cpp
translations/disk-encrypt.ts
translations/disk-encrypt_zh_CN.ts

Add error information
Log: fix issue
Bug: https://pms.uniontech.com/bug-view-258231.html

fix: [disk-encrypt] Add error information

---

.reuse/dep5
CMakeLists.txt
assets/polkit/policy/org.deepin.filemanager.diskencrypt.policy
debian/control
debian/dfmplugin-disk-encrypt.install
debian/dfmplugin-disk-encrypt.postinst
src/CMakeLists.txt
src/dde-desktop/CMakeLists.txt
src/dde-file-manager-daemon/CMakeLists.txt
src/dde-file-manager/dfmplugin-disk-encrypt-entry/dfmplugin_disk_encrypt_global.h
src/service/CMakeLists.txt
src/service/diskencrypt/CMakeLists.txt
src/service/diskencrypt/deepin-diskencrypt-service.json
src/service/diskencrypt/diskencrypt_global.h
src/service/diskencrypt/diskencryptdbus.cpp
src/service/diskencrypt/diskencryptdbus.h
src/service/diskencrypt/diskencryptdbus.xml
src/service/diskencrypt/encrypt/diskencrypt.cpp
src/service/diskencrypt/encrypt/diskencrypt.h
src/service/diskencrypt/encrypt/encryptworker.cpp
src/service/diskencrypt/encrypt/encryptworker.h
src/service/diskencrypt/fsresize/fsresize.cpp
src/service/diskencrypt/fsresize/fsresize.h
src/service/diskencrypt/globaltypesdefine.h
src/service/diskencrypt/main.cpp
src/service/diskencrypt/notification/notifications.cpp
src/service/diskencrypt/notification/notifications.h
src/service/diskencrypt/org.deepin.Filemanager.DiskEncrypt.service
src/service/diskencrypt/org.deepin.filemanager.diskencrypt.conf

install diskencrypt dbus plugin to deepin-service-manager
Log: daemon process refactor

refactor: daemon refactor

---

CMakeLists.txt
src/dde-file-manager-daemon/CMakeLists.txt
src/service/CMakeLists.txt

add compile option for diskencrypt service
Log: add cmake option

chore: add cmake option

---

debian/control

chore: add depends

---

debian/control

chore: change depends

---

debian/control

fix: depends file

---

src/dde-file-manager-daemon/daemonplugin-file-encrypt/encrypt/diskencrypt.cpp

The seek pos is greater than part size.
add limit for this.
Change-Id: I07839506f171858152ce2865f812714769023d9e

fix: [disk-encrypt] unencrypt part error

---

src/dde-file-manager/dfmplugin-disk-encrypt-entry/menu/diskencryptmenuscene.cpp
src/dde-file-manager/dfmplugin-disk-encrypt-entry/utils/encryptutils.cpp
translations/disk-encrypt.ts
translations/disk-encrypt_bo.ts
translations/disk-encrypt_ug.ts
translations/disk-encrypt_zh_CN.ts
translations/disk-encrypt_zh_HK.ts
translations/disk-encrypt_zh_TW.ts

as above.
Log: as above.
Bug: https://pms.uniontech.com/bug-view-275377.html

fix: [encrypt] add mixium size limit.

---

debian/changelog
debian/control

as above.
and bump version.
Log: as above.

chore: add dependency for recovery key generate.
